import Head from 'next/head'
import { GetStaticProps } from 'next'
import Layout from '../components/Layout'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { FlashcardProps } from '../components/Flashcard.js'
import { FlashcardModule } from '../components/FlashcardModule'
import prisma from '../../lib/prisma'

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps: GetStaticProps = async () => {
  let feed = await prisma.flashcard.findMany();
  feed = JSON.parse(JSON.stringify(feed))
  return {
    props: { feed }
  };
};

type Props = {
  feed: FlashcardProps[]
}

export default function Home(props: Props) {
  const { feed } = props
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <FlashcardModule flashcards={feed} />
      </main>
    </Layout>
  )
}
